# catalog-service/docker-compose.yml
version: '3.8'

services:
  catalog_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-service-app
    volumes:
      - .:/var/www
    networks:
      - zama_net
    depends_on:
      catalog_db:
        condition: service_healthy

  catalog_web:
    image: nginx:alpine
    container_name: catalog-service-nginx
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zama_net
    depends_on:
      - catalog_app

  catalog_db:
    image: mysql:8.0
    container_name: mysql_catalog_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_services
      MYSQL_USER: zama_user
      MYSQL_PASSWORD: secret
    volumes:
      - catalog_db_data:/var/lib/mysql
    networks:
      - zama_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  zama_net:
    external: true

volumes:
  catalog_db_data:
